Testing Aufgaben
djgogo/Exercises pull request #35
Opened 2016-10-11 15:11 UTC by djgogo

2016-10-17 09:23 UTC, FloEberle requested changes

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe2/c/Recognizer.php
> +    private $similarMessages = [
ich glaube nicht, dass sebastian hier eine hardcodierte liste von möglichkeiten erwartet hat, sondern einen schlauen algorithmus in der recognize() Methode, welcher "tolerant gegenüber einem fehlerhaften Zeichen in einer Nachricht ist."
Ich erwarte das ebenfalls ;)

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe2/d/Textdatei d2
> +Keine Ahnung was Sebastian mit dieser Frage meint und worauf er hinaus will?!
Paar Denkanstösse:
- Worduch weisst du ohne Pause zwischen den Zeichen, wann es endet?
- Was passiert mit Morsezeichen, welche nur 3 Signale lang sind?

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe3/ShoppingCartTest.php
> +class ShoppingCartTest extends \PHPUnit_Framework_TestCase
"Natürlich soll dabei jeder Test jeweils nur einen Aspekt des zu testenden Codes abdecken."

Ist meiner Meinung nach nicht optimal erfüllt mit deinen Tests. (Zu wenig granular)
- Testen ob der WK initial leer ist
- Testen was passiert bei RemoveItem ohne das Item im Cart zu finden
- Testen des Totals mit leerem Warenkorb

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/a/ShoppingCartControllerTest.php
> +            ->with(null)
??

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/a/ShoppingCartControllerTest.php
> +        $customerId = '';
??

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/b/Textdatei b4
> +desto komplizierter der Test.
Welche APIs sind denn hier impliziert? (Beispiele) Und wieso ist das mühsam zum Tests schreiben?

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/c/Textdatei c4.txt
> +Die Request- und Response Interfaces (allgeimein Response und Requests) sollten in getrennten Controllern verarbeitet
Muss nicht sein meiner Meinung nach

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/c/Textdatei c4.txt
> +Kunden-Nummer dann von der Session und nach der Verarbeitung gibt der Kontroller den Re-Direct Link zurück für go oder nicht gut.
Wo siehst du Session?

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/c/Textdatei c4.txt
> +Die Daten direkt in die Response zu schreiben ist schon aus Sicherheitsgründen nicht gut.
Wieso denn? Verstehe ich nicht..

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe4/c/Textdatei c4.txt
> +Die Daten direkt in die Response zu schreiben ist schon aus Sicherheitsgründen nicht gut.
Gibts vielleicht hier auch die Möglichkeit, explizitere APIs einzuziehen?

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe5/a/Textdatei 5 a1
> +je einen Test für jede mögliche Variante (6 Verzweigungen):
genau. deshalb sind methoden je mehr parameter sie haben umso schwerer zu testen! (wobei 2 von den 6 Verzweigungen keinen Einfluss haben)

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe6/Textdatei 6a
> +Name sehr schlecht gewählt, zu wenig aussagekräftig. Ein Datenbanktest muss die folgende Klasse extenden:
Wie kommst du darauf, dass das Backend auf einer Datenbank operiert?

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe6/Textdatei 6a
> +$this->assertFileEquals() oder $this->assertStringEqualsFile()
Die Zusicherung auf die vom Backend gespeicherten Werte fehlt komplett (Die Kernaufgabe der Methode)

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe6/Textdatei 6b
> +        $foo->operation($bar);
Hier wird weiterhin eine Methode auf dem Mock :exclamation: ausgeführt und nicht auf dem echten Objekt. Also auch deine Variante ist weiterhin falsch

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe6/Textdatei 6c
> +Hier findet gar kein Test statt! und die KOllaborator Klasse Bar darf ein Mock sein. der Test könnte z.B. wie folgt aussehen:
genau. entscheidend ist es FINDET KEINE ZUSICHERUNG statt.

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe6/Textdatei 6d
> +Bei grossen Parameter Mengen die getestet werden müssen kann oder sollte ein Dataprovider angewendet werden. Beispiel:
das ist eine gute idee. wichtig ist auch, dass hier ein test pro assertion sinn machen würde.

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe7/LegacyControllerTest.php
> +        define('DSN', 'sqlite::memory:');
?

2016-10-17 09:23 UTC, FloEberle commented on Testing/aufgabe8/a/LegacyController.php
> +        $statement = $this->db->prepare('SELECT * FROM users WHERE id=:user;');
schon viel besser. evtl den datenbank code noch aus dem controller wegrefactoren mittels backend/gateway

2016-10-17 09:23 UTC, FloEberle commented
aufgabe 9 und 10 habe ich nur überflogen..

2016-10-28 07:54 UTC, djgogo commented on Testing/aufgabe3/ShoppingCartTest.php
> +class ShoppingCartTest extends \PHPUnit_Framework_TestCase
Tests betreffend leerem Warenkorb sind mit dem gegebenen Code nicht möglich, da null returned wird und somit der test auf die Schnauze fällt. Ich müsste den zu testenden Code anpassen um diese Tests durchführen zu können, was aber nicht vorgesehen ist. Gemäss Aufgabe muss ich nur den gegebenen Code testen ohne Ihn anzupassen.

2016-11-04 10:21 UTC, merged