some improvements
djgogo/Exercises pull request #43
Opened 2016-11-23 15:11 UTC by djgogo

2016-11-28 07:29 UTC, FloEberle commented on TheSuXXStore/src/Controllers/CommentController.php
> +            $this->commentFormCommand->execute($request);
warum wird der returnvalue nicht mehr ausgewertet?

2016-11-28 07:47 UTC, FloEberle requested changes

2016-11-28 07:47 UTC, FloEberle commented on TheSuXXStore/src/Factories/Factory.php
> +        public function getErrorLogger() : ErrorLogger
:+1:

2016-11-28 07:47 UTC, FloEberle commented on TheSuXXStore/logs/error.log
> +2016/11/23 10:50:15 / Wrong mySql Credentials or mySql Database down / SQLSTATE[HY000] [1045] Access denied for user 'anyUser'@'localhost' (using password: YES)/1045 / /var/www/Exercises/TheSuXXStore
das file gehört ins gitinore!

2016-11-28 07:47 UTC, FloEberle commented on TheSuXXStore/src/Forms/FormError.php
> +            return '';
das ist super verwirrend. ein wert wird nicht gefunden und es wird ein leerer string retourniert. Hier wäre doch eine Exception richtig oder?

2016-11-28 07:47 UTC, FloEberle commented on TheSuXXStore/src/Forms/FormPopulate.php
> +            return '';
das ist super verwirrend. ein wert wird nicht gefunden und es wird ein leerer string retourniert. Hier wäre doch eine Exception richtig oder?

2016-11-28 07:47 UTC, FloEberle commented on TheSuXXStore/src/Http/Request.php
> +                throw new RequestValueNotFoundException('Value Not Found');
genauso! Exception und Tot! ;)

2016-11-28 07:47 UTC, FloEberle commented on TheSuXXStore/tests/Entities/CommentTest.php
> +            $reflectionProperty = $this->reflection->getProperty('cid');
das ist nicht so wie wir es vorgesehen haben mit der privaten methode.. immer noch viel copy :spaghetti:

2016-11-28 10:28 UTC, djgogo commented on TheSuXXStore/src/Controllers/CommentController.php
> +            $this->commentFormCommand->execute($request);
weil es in beiden fällen den exaktt selben redirect setzt und somit überflüssig war. also die exakt selbe ausgabe stattfindet. falls ein fehler auftritt wird eine fehlermeldung im view ausgegeben.

2016-11-28 11:25 UTC, djgogo commented on TheSuXXStore/src/Forms/FormError.php
> +            return '';
kann schon sein, muss aber so sein. denn dieser getter wird von der view benutzt. entweder zeigt er was an oder wenn er leer ist nichts an. eine exception kann der view nicht handeln. es ist extra so gelöst. falls du eine andere methode kennst wie ich die fehler anzeigen kann ohne den getter zu benutzen bin ich froh um inputs.

2016-11-28 11:25 UTC, djgogo commented on TheSuXXStore/src/Forms/FormPopulate.php
> +            return '';
dito

2016-11-28 11:27 UTC, djgogo commented on TheSuXXStore/tests/Entities/CommentTest.php
> +            $reflectionProperty = $this->reflection->getProperty('cid');
da ist was schief gelaufen, den hab ich 100%ig auch angepasst gehabt. strange

2016-11-28 11:28 UTC, djgogo commented on TheSuXXStore/src/Http/Request.php
> +                throw new RequestValueNotFoundException('Value Not Found');
voll brutal :)

2016-11-28 11:37 UTC, djgogo commented on TheSuXXStore/src/Forms/FormError.php
> +            return '';
das ist extra so gewollt, da dieser getter vom view benutzt wird. er zeigt was an falls da was ist, falls nicht muss es leer sein, eine exception kann der view jedenfalls nicht fangen. falls du eine bessere lösung für die anzeige der fehler kennst wäre ich froh um input :-)

2016-11-28 11:37 UTC, djgogo commented on TheSuXXStore/src/Forms/FormPopulate.php
> +            return '';
dito

2016-11-28 11:47 UTC, djgogo commented on TheSuXXStore/logs/error.log
> +2016/11/23 10:50:15 / Wrong mySql Credentials or mySql Database down / SQLSTATE[HY000] [1045] Access denied for user 'anyUser'@'localhost' (using password: YES)/1045 / /var/www/Exercises/TheSuXXStore
war beim ersten commit nicht drin, leider wird es nicht gelöscht wenn man es nachträglich ins .gitignore reintut

2016-11-29 10:15 UTC, FloEberle commented on TheSuXXStore/src/Controllers/CommentController.php
> +            $this->commentFormCommand->execute($request);
alles klar

2016-11-29 10:16 UTC, FloEberle commented on TheSuXXStore/logs/error.log
> +2016/11/23 10:50:15 / Wrong mySql Credentials or mySql Database down / SQLSTATE[HY000] [1045] Access denied for user 'anyUser'@'localhost' (using password: YES)/1045 / /var/www/Exercises/TheSuXXStore
versuch mal rauszufinden, wie du das aus git wieder entfernen kannst ;)

2016-11-29 10:17 UTC, FloEberle commented on TheSuXXStore/src/Forms/FormError.php
> +            return '';
der $default war auf jeden fall besser von vorher. zumindest explizit.

2016-11-29 10:17 UTC, FloEberle commented on TheSuXXStore/src/Forms/FormPopulate.php
> +            return '';
dito dito ;)

2016-11-30 07:00 UTC, merged